### PR TITLE
ROS 2 port of cmd_vel_mux

### PR DESCRIPTION
**Pull request by clalancette**
There's more information in the individual commits, but the basic sequence here goes like this:

1.  Import the original yocs_cmd_vel_mux from https://github.com/yujinrobot/yujin_ocs/tree/devel/yocs_cmd_vel_mux
1.  Do a bunch of cleanup on that old code
1.  Rename yocs_cmd_vel_mux -> cmd_vel_mux
1.  Port to ROS 2
1.  Make it so that parameters are much nicer
1.  Add in tests.

@stonier Review on this is appreciated!

### CODE REVIEW

**Comment by Paul-Ajay** [comment]
Any plans to merge this soon? @clalancette @stonier

**Comment by clalancette** [comment]
@stonier While you are looking at Kobuki stuff, this is related.  Thanks.

**Comment by stonier** [comment]
Big PR, but at a glance it looks sane. Not sure I'm keen to parse it with a fine tooth comb, but since we have nothing that will break (can you break a README? :P) let's get it in. I'll start submitting PR's / asking questions as I road test it over the coming days.

**Comment by stonier** [comment]
Started #3 to track follow-up jobs to this.

**Comment by stonier** [comment]
@clalancette Can you keep your branch around for a bit? Thanks.

**Pull request merged**
